services:
  code-editor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-1.0.0}
        TIMEZONE: America/Mexico_City
    container_name: lazyvim
    hostname: lazyvim-dev
    restart: unless-stopped
    volumes:
      #* Persistent dotfiles
      - .dotfiles/.zshrc:/home/developer/.zshrc
      - .dotfiles/.p10k.zsh:/home/developer/.p10k.zsh
      - .dotfiles/.config/lazygit:/home/developer/.config/lazygit
      - .dotfiles/.config/nvim:/home/developer/.config/nvim
      
      #* Cache directories for better performance
      - nvim-cache:/home/developer/.cache/nvim
      - zsh-cache:/home/developer/.cache/zsh
      - npm-cache:/home/developer/.npm
      - pip-cache:/home/developer/.cache/pip

      #* Mount directories
      #* Uncomment and modify the appropriate lines below

      #* Mount the user's Documents directory
      # - $HOME/Documents:/home/developer/Documents
      
      #* Mount the user's USB on macOS
      # - /Volumes/USB_NAME:/home/developer/usb
      
      #* Mount the user's USB on Linux
      # - /media/$USER/USB_NAME:/home/developer/usb
      
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - TZ=America/Mexico_City
    stdin_open: true
    tty: true

#* Named volumes for better performance and persistence
volumes:
  nvim-cache:
    driver: local
  zsh-cache:
    driver: local
  npm-cache:
    driver: local
  pip-cache:
    driver: local
