services:
  code-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazyvim
    volumes:
      - ~/.dotfiles:/home/develop/.dotfiles
    stdin_open: true
    tty: true